### ISSUE TITLE
Unable to move token at all

### ISSUE THREAD

**Issue by AJAnderson** [Exote/foundry-vtt-pathfinding#10]
I've installed the latest beta of foundry vtt (0.5.6). I'm using route finder 0.3.8.

I am unable to move a token at all. Once I enable route finder after selecting a token, the left mouse button does nothing. I can't drag or click and have any effect.

I have made sure the game is not paused.

**Comment by Exote** [comment]
Thanks for raising this, there are a lot of changes to the mouse interactions in 0.5.6. Looks like mousemove events are being cancelled. 

Should be fixed by: [https://gitlab.com/foundrynet/foundryvtt/-/issues/2821](https://gitlab.com/foundrynet/foundryvtt/-/issues/2821)

**Comment by Exote** [comment]
Should be fixed with v0.3.9
