### ISSUE TITLE
Clicking Route Finder icon again should toggle route finder off

### ISSUE THREAD

**Issue by AJAnderson** [Exote/foundry-vtt-pathfinding#11]
As per title, noticed this was somewhat unintuitive behaviour given how the other icons behave.

**Comment by Exote** [comment]
I think the difference between the route finder tool and some others is that it isn't really possible to do anything else while the tool is active. The toggle option is only useful if it doesn't interfere with other tools.

If it was a toggle you could leave the route finder tool on and try to use the ruler, which would be a bit of a confusing mess.

**Comment by AJAnderson** [comment]
Ah fair enough
