### ISSUE TITLE
Severe 0.5.7 Compability issues

### ISSUE THREAD

**Issue by Norc** [Exote/foundry-vtt-pathfinding#12]
RouteFinder is working better than in 0.5.6, but it is still essentially non-functional.

1. With a selected token and the Routefinder tool active, the path to mouse location is not drawn reliably. If it does manage to be drawn, it does not move fluidly or is sometimes invisibile, but in such cases the right-click to move the token does work.
2. Console errors appear very frequently in the console as I try to use the module:

![image](https://user-images.githubusercontent.com/64667579/82133731-75d92680-97bd-11ea-916e-5c9e3fa954f3.png)

These tests were run with RouteFinder 0.3.8 with RouteFinder as the only module installed.

**Comment by Exote** [comment]
With all the new changes to the mouse events, the module is currently broken. Hoping for some changes to Foundry to help fix it.

**Comment by Exote** [comment]
Should be fixed with v0.3.9
