### ISSUE TITLE
updated to 0.6.0 - getting cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by dipndawtz** [Exote/foundry-vtt-pathfinding#15]
![image](https://user-images.githubusercontent.com/38708687/82715045-5d568980-9c5f-11ea-9bd8-6b9edb406372.png)

As the title says, I upgraded foundry to version 0.6.0 (using the latest version of route finder - 0.3.9) and whenever I try to click the route finder button I get the above error.

**Comment by Varstahl** [comment]
I don't know if it's related, but I've heard from my GM that what was previously provided to the API as lists are now returned as hashmaps. That might be the problem, but I'm not sure, came in here to see if it was a known problem or a problem with my setup.
